### PR TITLE
Default server config domain

### PR DESCRIPTION
**Pull request by thiagotalma**
Should not the domain be defined here?
The `avahi__domain` setting has no effect.

### CODE REVIEW

**Comment by thiagotalma** [comment]
Oops! With the domain set things do not work well with tinc...

**Comment by drybjed** [comment]
At the moment `avahi__domain` variable is used to generate correct host addresses and CNAME aliases. I'm not sure if it should be explicitly set in the configuration file. Did you plan to change the Avahi domain this way?

It looks like the issue is with Sphinx on Travis, not with your changes. The issue seems to be in all tests, I'll look into it.

**Comment by thiagotalma** [comment]
I just wanted to use `server.vpn` instead of `server.local`  😉 

But it really does not make that much difference...

I'll close the PR.

**Comment by drybjed** [comment]
You can still define it in the inventory if you want, via `avahi__daemon_conf_server`, but cause issues if applications expect Avahi domain to be `.local` explicitly. YMMV.

**Pull request closed without merging**
